### ISSUE TITLE
Touch Edge of Screen No Response

### ISSUE THREAD

**Issue by brandlee** [qs-lll/ExpandingPager#8]
First, thx for your wonderful library,but there is a problem,when I touch the edge of screen trying to move the card,it doesn't response,because you resize the width of viewpager,so what can we do to fix this?Looking forward to your resolution.

**Comment by qs-lll** [comment]
u can use dispatchTouchEvent()  to viewpager from parent

**Comment by brandlee** [comment]
thx, I just fix this problem, appreciate for your reply:
`root_view.setOnTouchListener(new View.OnTouchListener() {`
            `@Override`
            `public boolean onTouch(View v, MotionEvent event) {`
                `return mViewPager.dispatchTouchEvent(event);`
            `}`
       `});`

**Comment by qs-lll** [comment]
:> 为啥不直接搞中文...  看英文很累的
